# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9c4a6bac30a3ca60c3b8b729f063d42d8f301ace8c603454dd9c52b6992d6c486c5f716f92b10522927fe0fafae48d988713e1d84ab9894905fed407cbab779c

test:
  secret_key_base: 08b958b4a08e7df5d46eaaad753604d6fd750b565d17c5c4bbd3920b4ae26842bbb624e93a84ce83fde0b1e4b8393cea3346159013ed955e3aa60336ec49a7a8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
